### ISSUE TITLE
logparser python3兼容性

### ISSUE THREAD

**Issue by zhujiem** [logpai/loghub-2.0#1]
想问LogPub/benchmark/logparser的所有parser代码都进行py2->py3转换和测试吗？

**Comment by zhjiang22** [comment]
Yes, all log parsers can be run on both Loghub-2k and LogPub in a Python 3.8 environment, provided that the necessary requirements have been installed.

**Comment by zhujiem** [comment]
测试2k样本使用的是xx_2k.log_structured.csv还是xx_2k.log_structured_corrected.csv  
_corrected.csv对应的来源是哪里，与原_structured.csv的区别是什么？

**Comment by zhjiang22** [comment]
```xx_2k.log_structured_corrected.csv``` is the label files proposed by [Guidelines for assessing the accuracy of log message template identification techniques](https://dl.acm.org/doi/abs/10.1145/3510003.3510101). They apply some heuristic rules to fix incorrect templates in the original Loghub-2k. 
The user can specify which file to utilize: if the -otc is appended, the ```xx_2k.log_structured_corrected.csv``` files will be employed. In our benchmark, we opt for the ```xx_2k.log_structured_corrected.csv``` files, as it has already been adopted by recent studies.

**Comment by zhujiem** [comment]
> 想问LogPub/benchmark/logparser的所有parser代码都进行py2->py3转换和测试吗？

Py2->Py3的转换是你完成的还是其他工作完成的？我想合入到logparser.

Guidelines for assessing这篇有repo吗？没有看到

**Comment by zhjiang22** [comment]
> > 想问LogPub/benchmark/logparser的所有parser代码都进行py2->py3转换和测试吗？
> 
> Py2->Py3的转换是你完成的还是其他工作完成的？我想合入到logparser.
> 
> Guidelines for assessing这篇有repo吗？没有看到

The repo of it is available at [figshare](https://figshare.com/articles/software/Artifact_for_Guidelines_for_Assessing_the_Accuracy_of_Log_Message_Template_Identification_Techniques_/18858332).
I modify the code based on it, and fix all problems when using Py3.
