### ISSUE TITLE
About Labels...

### ISSUE THREAD

**Issue by Sun-HR02** [logpai/loghub-2.0#10]
Thank you for your work! The dataset really helps!

For the full_datasets, how can I get the labels? I currently understand how to get labels in BGL but I still have difficulty in other datasets. Thank you anyway!

**Comment by zhjiang22** [comment]
Hi, thanks for your interest! Could you please clarify what you mean by "the labels"? If you are referring to the parsing ground truth, I believe all datasets are in the same format. You can find it in the [dataset]_full.log_structured.csv file.

**Comment by Sun-HR02** [comment]
> Hi, thanks for your interest! Could you please clarify what you mean by "the labels"? If you are referring to the parsing ground truth, I believe all datasets are in the same format. You can find it in the [dataset]_full.log_structured.csv file.

Thank you for your reply. I'm currently studying in log-based anomaly detection. In LogHub, we can get labels(normal or abnormal) in several datasets, e.g. HDFS and BGL. Are LogHub2.0 full_datasets labelled for AD?

**Comment by zhjiang22** [comment]
Thank you for your clarification. Loghub-2.0 is designed for evaluating log parsing techniques and therefore does not include labels for log-based anomaly detection. However, you can try matching the logs in Loghub to our labeled log templates using regular expressions. You can find the labeled log templates in the file named "[dataset]_full.log_templates.csv". Additionally, this [regexmatch.py file](https://github.com/logpai/logparser/blob/main/logparser/logmatch/regexmatch.py) in the logparser repository might be useful for you.

**Comment by Sun-HR02** [comment]
> Thank you for your clarification. Loghub-2.0 is designed for evaluating log parsing techniques and therefore does not include labels for log-based anomaly detection. However, you can try matching the logs in Loghub to our labeled log templates using regular expressions. You can find the labeled log templates in the file named "[dataset]_full.log_templates.csv". Additionally, this [regexmatch.py file](https://github.com/logpai/logparser/blob/main/logparser/logmatch/regexmatch.py) in the logparser repository might be useful for you.

Thank you for the advice. Sorry for misunderstanding the project. I wonder whether Loghub 2.0 uses the same raw logs as Loghub. Is the increase in the number of templates due to better parsing techniques rather than new data?

**Comment by zhjiang22** [comment]
> > Thank you for your clarification. Loghub-2.0 is designed for evaluating log parsing techniques and therefore does not include labels for log-based anomaly detection. However, you can try matching the logs in Loghub to our labeled log templates using regular expressions. You can find the labeled log templates in the file named "[dataset]_full.log_templates.csv". Additionally, this [regexmatch.py file](https://github.com/logpai/logparser/blob/main/logparser/logmatch/regexmatch.py) in the logparser repository might be useful for you.
> 
> Thank you for the advice. Sorry for misunderstanding the project. I wonder whether Loghub 2.0 uses the same raw logs as Loghub. Is the increase in the number of templates due to better parsing techniques rather than new data?

As described in our paper, we use the original Loghub datasets for annotation, only cleaning a small portion of meaningless logs. Therefore, the raw logs in Loghub-2.0 are a subset of the raw logs in Loghub, comprising the majority of the data.

**Comment by Sun-HR02** [comment]
Thank you for the reply! I will try to match tha new templates to Loghub.
