### ISSUE TITLE
Drain depth

### ISSUE THREAD

**Issue by IsabelleQin** [logpai/loghub-2.0#11]
Hi! I noticed that in Drain's treeSearch and addSeqToPrefixTree function, the depth comparisons use ">=" instead of ">." That said, the search will terminate before the last depth without creating/searching on the deepest depth, which seems not very similar to the paper. In the Sec. 3-D, Drain is said to use the first token as the only binning layer if the depth is 3. However, when examining with Proxifier, whose default depth is also 3, no token is used as the 3rd layer bin. 

This result is generated by inserting:
``print(token)``
on line 73.

And the depth comparison code I'm referring to are:
line71 &72:
``          if currentDepth >= self.depth or currentDepth > seqLen:
                break
``
and line102:
``            if currentDepth >= self.depth or currentDepth > seqLen: ....``

Can you please confirm whether these pieces of code are correct? Thanks:-))

**Comment by zhjiang22** [comment]
Thank you for your interest in our work!

Firstly, the implementation of Drain is reused from the [logparser](https://github.com/logpai/logparser/blob/main/logparser/Drain/Drain.py) project, and it aligns with the implementation in the [original Drain3 package](https://github.com/logpai/Drain3/blob/master/drain3/drain.py).

Additionally, I agree with your observation regarding the small difference between this code and the description in the original Drain paper. Specifically, the code implements "self.depth = depth - 2" and that currentDepth starts at 1. Furthermore, the original comments in [Drain.py](https://github.com/logpai/Drain3/blob/master/drain3/drain.py) state:

```python
"""
:param depth: max depth levels of log clusters. Minimum is 3.
For example, for depth==4, Root is considered depth level 1.
Token count is considered depth level 2.
First log token is considered depth level 3.
Log clusters below the first token node are considered depth level 4.
"""
```

I believe this is a minor boundary setting that should not affect the results. Just follow the definition of depth in the code implementation. You might consider that this depth includes the leaf nodes of log groups, which provides a more appropriate and concrete definition for the "depth" of the parsing tree.

Please let me know if you have any further questions! 😊

**Comment by IsabelleQin** [comment]
That makes sense, thanks!
