### ISSUE TITLE
Meaning of the data in `efficiency_results.csv`

### ISSUE THREAD

**Issue by lizeyan** [logpai/loghub-2.0#2]
![image](https://github.com/logpai/LogPub/assets/12494243/b8c19090-e9da-40d1-89dc-fdff59fd6a56)

It is inspiring to read your excellent work. However, I'm not quite clear on the meaning of the numbers in `efficiency_results.csv`. Could you please provide more explanations?

**Comment by lizeyan** [comment]
And what are the numbers in `RQs_experiments/RQ2/effectiveness_results.csv` mean? (before `/` and after `/`)

**Comment by zhjiang22** [comment]
Thank you for your interest. As described in our paper, the two CSV files contain detailed parsing time (in seconds) and metric scores of our benchmark. The figures before the slash (/) represent the results on Loghub-2k, while those after the slash (/) represent the results on LogPub. In addition, the -1 means this log parser cannot parse this dataset within a reasonable time (12 hours in our experiments).
