### ISSUE TITLE
License完善

### ISSUE THREAD

**Issue by zhujiem** [logpai/loghub-2.0#3]
1. 2k_dataset目录下缺失License，请复制https://github.com/logpai/loghub/blob/master/LICENSE 到2k_dataset/LICENSE
2. 2k_dataset下的每个子目录需要添加对应的README，每个数据集对应从loghub子目录复制过来，如Apache的：      https://github.com/logpai/loghub/blob/master/Apache/README.md   每个README都不一样，需要单独copy
3. 修改2k_dataset/README，增加loghub credit
4. benchmark/logparser每个方法缺失LICENSE，从logparser对应的目录拷过来，如https://github.com/logpai/logparser/blob/main/logparser/AEL/LICENSE  每个LICENSE都不一样，需要单独copy
5. 修改https://github.com/logpai/Loghub-2.0/blob/main/LICENSE   文件，主要对数据使用进行规范，MIT部分可以去掉。请参考:
```
LICENSE OF LOGHUB-2.0

The datasets are freely available for research or academic work, subject to 
the following condition: For any usage or distribution of the loghub-2.0 datasets,
please refer to the loghub repository URL (https://github.com/logpai/loghub-2.0)
and cite the following loghub papers where applicable.

+ Zhihan Jiang, Jinyang Liu, Junjie Huang, Yichen Li, Yintong Huo, Jiazhen Gu, 
   Zhuangbin Chen, Jieming Zhu, Michael R. Lyu. A Large-scale Evaluation for 
   Log Parsing Techniques: How Far are We? In ISSTA, 2024.
+ Jieming Zhu, Shilin He, Pinjia He, Jinyang Liu, Michael R. Lyu. Loghub: A Large 
   Collection of System Log Datasets for AI-driven Log Analytics. In ISSRE, 2023.

The above license notice shall be included in all copies of the datasets.
```

6. 在README这句下面please cite the following papers添加loghub论文

**Comment by zhjiang22** [comment]
Updated. Please review the changes and let me know if there are still any other issues. Many thanks for your assistance! 😊

**Comment by zhujiem** [comment]
Great. Thanks!
