### ISSUE TITLE
FGA and FTA

### ISSUE THREAD

**Issue by gxa1028** [logpai/loghub-2.0#5]
What do FGA and FTA mean in the evaluation metrics?

**Comment by zhjiang22** [comment]
FGA is the template-level metric of grouping accuracy, while the FTA is another template level metric proposed by [[ICSE’22] Guidelines for assessing the accuracy of log message template identification techniques](https://dl.acm.org/doi/abs/10.1145/3510003.3510101). For more details, please refer to Section 4.2 of our paper [[ISSTA'24] A Large-Scale Evaluation for Log Parsing Techniques: How Far Are We?](https://arxiv.org/pdf/2308.10828).

**Comment by gxa1028** [comment]
Thanks, I have read this paper and understand
