### ISSUE TITLE
EventTemplate问题

### ISSUE THREAD

**Issue by yunlibo** [logpai/loghub-2.0#7]
你好，我想问一下在full中的EventTemplate是准确的吗？因为我发现了类似HPC_full.log_structured.csv里的inconsistent nodesets node-63 0x1c01dfffe <ok> node-32 0x1cffffffe <ok> node-34 0x1c1fffffe <ok> node-33 0x1cffffffe <ok>，为什么EventTemplate为inconsistent nodesets <*> <*> <ok> <*> <*> <ok>呢？   :)

**Comment by yunlibo** [comment]
不好意思，上述的EventTemplate为什么是inconsistent nodesets <*> <*> <ok> <*> <*> <ok>呢？

**Comment by yunlibo** [comment]
补充：EventTemplate中ok的个数

**Comment by zhjiang22** [comment]
Many thanks for identifying the errors. As mentioned in our paper, despite our careful review of the manually annotated log templates, errors may still occur due to the extensive human effort involved. We always welcome feedback from the community and will update our datasets accordingly later.
