### ISSUE TITLE
Drain cannot run

### ISSUE THREAD

**Issue by lezhang-thu** [logpai/loghub-2.0#9]
The following code might miss an extra `/`:
[https://github.com/logpai/loghub-2.0/blob/main/benchmark/logparser/Drain/Drain.py#L339](https://github.com/logpai/loghub-2.0/blob/main/benchmark/logparser/Drain/Drain.py#L339)

```
template_regex = re.sub(r'\\ +', r'\s+', template_regex)
```

`r'\s+'` should be `r'\\s+'`?

**Comment by zhjiang22** [comment]
Thank you very much for identifying this issue. We have now fixed it. Feel free to let us know if you have any other questions. :)
